analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#FEFEFE'
    - '#3C489C'
    - '#231F20'
    - '#E82C57'
    - '#98CA4D'
  rhythmicContrast: 0
typography_spectrum: 0.07588
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: World Nomad School
