name: World Nomad School
favicon: null
layout_spectrum: 0.93412
typography_spectrum: 0.6578599871136248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f479a'
    - '#000000'
    - '#e9185b'
    - '#97cc59'
  brandStrength: 0.4375
  lightness: 0.9470996127929538
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
