name: World Nomad School
favicon: null
layout_spectrum: 0.91244
typography_spectrum: 0.07588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f479a'
    - '#000000'
    - '#e9185b'
    - '#97cc59'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
